### PR TITLE
mention tuid

### PR DESCRIPTION
**Pull request by nosovk**

### CODE REVIEW

**Comment by kurtextrem** [comment]
Please also mention tuid uses `Math.random` in the JS implementation, making it less secure than the original UUID implementation (that uses the crypto module).

**Comment by nosovk** [comment]
Lol, never saw that there is a JS implementation there. It usually needed for generation of Primary Keys in databases (mostly PG). Using it allows substituting Serial with less predictable values, without dropping performance. And usually it's compiled C extension in PG.
But how @kurtextrem mentioned there is some JS implementation available. It's a good point that using JS for cryptography is a bad idea, and you should not rely on naive JS implementations because of security and performance issues. Better use official https://nodejs.org/api/crypto.html or something like https://www.npmjs.com/package/argon2, which uses bindings to C code under the hood.

**Comment by sw-yx** [comment]
Thanks a TON @nosovk and @kurtextrem  - i am surprised anyone is paying attention to this repo but this is why i open sourced my list!

i took the advantage to rearrange my list a little bit - have a look at my latest commit

do you have anything else to add? i'd love your input. really appreciate the add.

**Comment by kurtextrem** [comment]
I found your HackerNews thread interesting and the comments there, e.g. this [one](https://news.ycombinator.com/item?id=31719190) regarding verification of UUIDs. Maybe worth adding as 'ideas'?
Also, an interesting thread with opinions about the UUIDs randomness maybe even being an advantage: https://news.ycombinator.com/item?id=31721983. Curious about benchmarks now.

**Comment by kurtextrem** [comment]
Also, I got another set of tools that generate UUID similar things:
- A maintained ulid generator in Node https://www.npmjs.com/package/ulidx
- Faster nanoid generator https://github.com/rustq/napi-nanoid
- Yet another random ID generator https://www.npmjs.com/package/hyperid

**Pull request merged**
